### PR TITLE
Remove key from plugin

### PR DESCRIPTION
**Pull request by matt-oconnell**
Fixes issue #3 in Experiences

### CODE REVIEW

**Comment by matt-oconnell** [comment]
@artkay @tannernelson How should we go about this? Issue belongs to a seperate repo (https://github.com/BlueBiteLLC/system-experiences/issues/3)

**Comment by artkay** [comment]
@matt-oconnell Just close the issue from here with comment "Fixes #n" - that should work

**Comment by tannernelson** [comment]
:+1:

**Comment by matt-oconnell** [comment]
@artkay This is it's own repo, it doesn't recognize issues from `experiences` though..

**Comment by artkay** [comment]
@matt-oconnell actually it does:

 BlueBiteLLC/system-experiences#3

**Comment by artkay** [comment]
Just use the full prefix

**Comment by matt-oconnell** [comment]
Ah ok cool

**Pull request merged**
